export const specialtyData = [
     {
        name: "Cardiology",
        treatments: [
            "Electrocardiogram (ECG)",
            "Echocardiogram",
            "Stress Test",
            "Cardiac Catheterization",
            "Coronary Angioplasty",
            "Pacemaker Implantation",
            "Heart Failure Management",
            "Hypertension Treatment",
            "Arrhythmia Treatment",
        ],
    },
    {
        name: "Dermatology",
        treatments: [
            "Acne Treatment",
            "Laser Skin Resurfacing",
            "Botox Injections",
            "Mole Removal",
            "Skin Biopsy",
            "Psoriasis Treatment",
            "Eczema Treatment",
            "Melanoma Screening",
            "Hair Loss Treatment",
            "Chemical Peels",
        ],
    },
    {
        name: "Gynecology",
        treatments: [
            "Pap Smear",
            "Pelvic Ultrasound",
            "Endometriosis Treatment",
            "Menopause Management",
            "Fibroid Removal",
            "Ovarian Cyst Removal",
            "Contraceptive Counseling",
            "Hysterectomy",
        ],
    },
    {
        name: "Neurology",
        treatments: [
            "EEG (Electroencephalogram)",
            "MRI Brain Scan",
            "Stroke Rehabilitation",
            "Migraine Treatment",
            "Nerve Conduction Study",
            "Parkinson’s Disease Management",
            "Epilepsy Treatment",
            "Multiple Sclerosis Management",
        ],
    },
    {
        name: "Ophthalmology",
        treatments: [
            "Cataract Surgery",
            "Lasik Eye Surgery",
            "Glaucoma Treatment",
            "Retinal Detachment Repair",
            "Eye Injections for Macular Degeneration",
            "Strabismus Surgery",
            "Corneal Transplant",
        ],
    },
    {
        name: "Orthopedics",
        treatments: [
            "Joint Replacement Surgery",
            "Arthroscopy",
            "Fracture Repair",
            "Physical Therapy",
            "Spinal Surgery",
            "Sports Injury Treatment",
            "Carpal Tunnel Surgery",
            "Knee Arthroscopy",
        ],
    },
    {
        name: "Pediatrics",
        treatments: [
            "Newborn Checkups",
            "Childhood Immunizations",
            "Asthma Management",
            "Developmental Screening",
            "Nutritional Counseling",
            "ADHD Treatment",
            "Growth Monitoring",
        ],
    },
    {
        name: "Psychiatry",
        treatments: [
            "Cognitive Behavioral Therapy (CBT)",
            "Medication Management",
            "Addiction Counseling",
            "Electroconvulsive Therapy (ECT)",
            "Anxiety & Depression Treatment",
            "Bipolar Disorder Management",
            "Schizophrenia Treatment",
        ],
    },
    {
        name: "Urology",
        treatments: [
            "Kidney Stone Treatment",
            "Prostate Cancer Screening",
            "Bladder Control Therapy",
            "Vasectomy",
            "Urinary Tract Infection (UTI) Treatment",
            "Erectile Dysfunction Treatment",
        ],
    },
    {
        name: "Endocrinology",
        treatments: [
            "Diabetes Management",
            "Thyroid Disorder Treatment",
            "Hormone Therapy",
            "Osteoporosis Treatment",
            "Adrenal Gland Disorder Treatment",
        ],
    },
    {
        name: "Gastroenterology",
        treatments: [
            "Colonoscopy",
            "Endoscopy",
            "Liver Function Tests",
            "IBD Management",
            "Acid Reflux Treatment",
            "Gallstone Removal",
        ],
    },
    {
        name: "Oncology",
        treatments: [
            "Chemotherapy",
            "Radiation Therapy",
            "Immunotherapy",
            "Cancer Surgery",
            "Bone Marrow Transplant",
            "Breast Cancer Screening",
            "Prostate Cancer Treatment",
        ],
    },
    {
        name: "Pulmonology",
        treatments: [
            "Spirometry",
            "Pulmonary Function Tests",
            "Sleep Apnea Treatment",
            "Lung Cancer Screening",
            "COPD Management",
            "Asthma Control Therapy",
        ],
    },
    {
        name: "Allergy and Immunology",
        treatments: [
            "Allergy Skin Tests",
            "Immunotherapy (Allergy Shots)",
            "Asthma Management",
            "Food Allergy Treatment",
            "Sinusitis Treatment",
        ],
    },
    {
        name: "General Surgery",
        treatments: [
            "Appendectomy",
            "Hernia Repair",
            "Gallbladder Removal",
            "Breast Surgery",
            "Laparoscopic Surgery",
            "Thyroidectomy",
            "Colon Resection",
        ],
    },
    {
        name: "Plastic Surgery",
        treatments: [
            "Rhinoplasty (Nose Job)",
            "Liposuction",
            "Breast Augmentation",
            "Facelift",
            "Burn Reconstruction Surgery",
            "Abdominoplasty (Tummy Tuck)",
        ],
    },
    {
        name: "Nephrology",
        treatments: [
            "Dialysis",
            "Kidney Transplant Evaluation",
            "Chronic Kidney Disease Management",
            "Urinary Tract Infections Treatment",
        ],
    },
    {
        name: "Anesthesiology",
        treatments: [
            "General Anesthesia",
            "Spinal Anesthesia",
            "Pain Management Therapy",
            "Regional Anesthesia",
        ],
    },
    {
        name: "Emergency Medicine",
        treatments: [
            "Trauma Care",
            "Cardiac Arrest Resuscitation",
            "Severe Allergic Reaction Treatment",
            "Stroke Treatment",
        ],
    },
    {
        name: "Rheumatology",
        treatments: [
            "Arthritis Treatment",
            "Autoimmune Disease Management",
            "Lupus Treatment",
            "Osteoarthritis Therapy",
        ],
    },
    {
        name: "Radiology",
        treatments: [
            "X-Ray Imaging",
            "MRI Scans",
            "CT Scans",
            "Ultrasound Imaging",
            "PET Scans",
        ],
    },
    {
        name: "Physical Therapy",
        treatments: [
            "Rehabilitation Exercises",
            "Post-Surgical Recovery Therapy",
            "Sports Injury Rehabilitation",
            "Manual Therapy",
        ],
    },
    {
        name: "Otolaryngology (ENT)",
        treatments: [
            "Tonsillectomy",
            "Sinus Surgery",
            "Hearing Loss Treatment",
            "Cochlear Implant Surgery",
            "Sleep Apnea Surgery",
        ],
    },
    {
        name: "Vascular Surgery",
        treatments: [
            "Varicose Vein Surgery",
            "Aneurysm Repair",
            "Carotid Artery Surgery",
            "Peripheral Artery Disease Treatment",
        ],
    },
    {
        name: "Sports Medicine",
        treatments: [
            "ACL Injury Treatment",
            "Rotator Cuff Repair",
            "Concussion Management",
            "Sports Rehabilitation",
        ],
    },
    {
        name: "Geriatrics",
        treatments: [
            "Elderly Fall Prevention",
            "Dementia Care",
            "Osteoporosis Management",
            "Geriatric Nutrition Counseling",
        ],
    },
    {
        name: "Podiatry",
        treatments: [
            "Bunions Treatment",
            "Plantar Fasciitis Therapy",
            "Diabetic Foot Care",
            "Foot & Ankle Surgery",
        ],
    },
    {
        name: "Dentistry",
        treatments: [
            "Teeth Cleanings ",
            "Teeth Whitening ",
            "Extractions",
            "Veneers",
            "Fillings",
            "Crowns",
            "Root Canal",
            "Dentures",
            "Implants",
            "Braces",
            "Invisalign",
            "TMJ Treatment",
            "Gum Disease Treatment",
            "Oral Cancer Screening",
            "Pediatric Dentistry",
            "Orthodontics",
            "Periodontics",
            "Prosthodontics",
        ],
    },

    {
        name: "Speech Therapy",
        treatments: [
            "Articulation Therapy",
            "Language Intervention",
            "Fluency Shaping Techniques",
            "Voice Therapy",
            "Dysphagia Therapy",
            "Cognitive-Communication Therapy",
            "Accent Modification",
            "Accent Reduction",
            "Accent Neutralization",
            "Accent Training",
            "Accent Coaching",
            "Augmentative and Alternative Communication (AAC)",
            "Cognitive-Communication Therapy"
        ],
    },

    {
        name: "Nutrition",
        treatments: [
            "Medical Nutrition Therapy",
            "Digestive Disorders Nutrition",
            "Weight Management",
            "Diabetes Nutrition",
            "Heart Health Nutrition",
            "Sports Nutrition",
            "Prenatal Nutrition",
            "Pediatric Nutrition",
            "Metabolic and Endocrine Health",
            "Eating Disorders",
            "Sports performance",
            "Nutrition for Cancer",
        ],
    },

    {
        name: "Medical Ethics",
        treatments: [
            "Patient Right and Autonomy",
            "Informed Consent",
            "End-of-Life Care",
            "Medical Confidentiality",
            "Medical Records",
            "Medical Research",
            "Medical Decision Making",
            "Medical Professionalism",
            "Medical Malpractice",
            "Confidianlity and Data Protection",
        ],
    },
]